env = 'production'
[app]
deployLimit = 8
shutdownTimeout = 10
repositoryPath = ''

[cors]
enabled = false
origins = '*'
methods = 'GET, POST, PUT, DELETE, OPTIONS'
headers = 'X-API-KEY'
credentials = true

[cookie]
name = 'goploy_token'
expire = 86400

[jwt]
key = '2021-12-14 18:43:15.8805255 +0800 CST m=+0.004156701'

[db]
type = 'mysql'
user = 'root'
password = ''
host = '127.0.0.1'
port = '3306'
database = 'goploy'

[log]
path = 'stdout'

[web]
port = '80'

[ldap]
enabled = false
url = ''
bindDN = ''
password = ''
baseDN = ''
uid = ''
userFilter = ''

[dingtalk]
appKey = ''
appSecret = ''

[feishu]
appKey = ''
appSecret = ''