name: Docker Image CI

on:
  workflow_dispatch:
  release:
    types: [published, edited]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
          docker version
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
          # 使用Dockerfile构建镜像
          docker build -t zhenorzz/goploy . --file docker/Dockerfile 
          # 推送镜像到镜像仓库
          docker push zhenorzz/goploy
