name: Docker Image CI

on:
  workflow_dispatch:
  release:
    types: [published, released, created, edited]

jobs:

  build:

    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v2
    - name: Get version
      id: get_version
      run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "VERSION=${{ github.event.release.name }}" >> $GITHUB_ENV
          else
            echo "VERSION=latest" >> $GITHUB_ENV
          fi
   
    - name: Build the Docker image
      run: |
          docker version
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
          # 使用Dockerfile构建镜像
          docker build -t zhenorzz/goploy:${{ env.VERSION }} . --file docker/Dockerfile
          # 推送镜像到镜像仓库
          docker push zhenorzz/goploy:${{ env.VERSION }}
